openapi: 3.0.1
info:
  title: User V1
  version: v1
servers:
  - url: http://localhost:3000
paths:
  "/api/v1/users":
    post:
      summary: ユーザー作成
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - email
                - password
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        '201':
          description: ユーザー作成成功
        '400':
          description: 不正なリクエスト

  "/users/{user_id}/plans":
    get:
      summary: ユーザーの予定一覧を取得
      tags:
        - Plans
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: 取得成功
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Plan'

    post:
      summary: 新しい予定を作成
      tags:
        - Plans
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PlanInput'
      responses:
        '201':
          description: 作成成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Plan'
        '422':
          description: バリデーションエラー

  "/users/{user_id}/plans/{id}":
    get:
      summary: 予定の詳細を取得
      tags:
        - Plans
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: integer
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: 詳細取得成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Plan'

    put:
      summary: 予定の全更新
      tags:
        - Plans
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: integer
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PlanInput'
      responses:
        '200':
          description: 更新成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Plan'
        '422':
          description: バリデーションエラー

    delete:
      summary: 予定の削除
      tags:
        - Plans
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: integer
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: 削除成功

components:
  schemas:
    Plan:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        content:
          type: string
        start_time:
          type: string
          format: date-time
        end_time:
          type: string
          format: date-time
        user_id:
          type: integer
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    PlanInput:
      type: object
      required:
        - title
        - start_time
        - end_time
      properties:
        title:
          type: string
        content:
          type: string
        start_time:
          type: string
          format: date-time
        end_time:
          type: string
          format: date-time
